const express = require("express");
const mongoose = require("mongoose");
const Expense = require("../models/Expense");
const auth = require("../middleware/auth");
const { questionToQuery, generateAnswer, generateAnswerStream } = require("../services/gemini");

const router = express.Router();

router.use(auth);

// allowed aggregation stages (for safety)
const ALLOWED_STAGES = ["$match", "$group", "$sort", "$project", "$limit"];

// sanitize the pipeline generated by gemini
function sanitizePipeline(pipeline, userId) {
  if (!Array.isArray(pipeline)) return null;

  const sanitized = [];

  for (const stage of pipeline) {
    const keys = Object.keys(stage);
    if (keys.length !== 1) continue;

    const stageType = keys[0];
    if (!ALLOWED_STAGES.includes(stageType)) continue;

    // convert userId strings to ObjectId in $match stages
    if (stageType === "$match") {
      stage.$match.userId = new mongoose.Types.ObjectId(userId);

      // convert date strings to Date objects
      for (const [key, value] of Object.entries(stage.$match)) {
        if (key === "date" && typeof value === "object") {
          for (const [op, dateStr] of Object.entries(value)) {
            if (typeof dateStr === "string") {
              const d = new Date(dateStr);
              if (!isNaN(d.getTime())) {
                value[op] = d;
              }
            }
          }
        }
      }
    }

    sanitized.push(stage);
  }

  // make sure there's a $match stage with userId
  const hasUserMatch = sanitized.some(
    (s) => s.$match && s.$match.userId
  );

  if (!hasUserMatch) {
    sanitized.unshift({
      $match: { userId: new mongoose.Types.ObjectId(userId) },
    });
  }

  return sanitized;
}

// POST /api/chat
router.post("/", async (req, res) => {
  try {
    const { message } = req.body;

    if (!message || !message.trim()) {
      return res.status(400).json({ message: "Message is required" });
    }

    // step 1: translate question to mongodb pipeline
    const pipeline = await questionToQuery(message, req.userId);

    if (!pipeline) {
      return res.status(422).json({
        message: "I couldn't understand that question. Try rephrasing it.",
      });
    }

    // step 2: sanitize and validate the pipeline
    const safePipeline = sanitizePipeline(pipeline, req.userId);

    if (!safePipeline || safePipeline.length === 0) {
      return res.status(422).json({
        message: "I couldn't generate a valid query. Try a simpler question.",
      });
    }

    // step 3: run the query
    let queryResult;
    try {
      queryResult = await Expense.aggregate(safePipeline);
    } catch (queryErr) {
      console.error("Query execution error:", queryErr.message);
      return res.status(422).json({
        message: "The query failed to execute. Try rephrasing your question.",
      });
    }

    // step 4: generate natural language answer
    const answer = await generateAnswer(message, queryResult);

    res.json({ answer, data: queryResult });
  } catch (err) {
    console.error("Chat error:", err);
    res.status(500).json({ message: "Something went wrong. Please try again." });
  }
});
// POST /api/chat/stream
router.post("/stream", async (req, res) => {
  try {
    const { message } = req.body;
    if (!message || !message.trim()) {
      return res.status(400).json({ message: "Message is required" });
    }

    // Set headers for SSE
    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");

    // 1. translate question
    const pipeline = await questionToQuery(message, req.userId);
    if (!pipeline) {
      res.write(`data: ${JSON.stringify({ error: "I couldn't understand that question. Try rephrasing it." })}\n\n`);
      return res.end();
    }

    // 2. sanitize
    const safePipeline = sanitizePipeline(pipeline, req.userId);
    if (!safePipeline || safePipeline.length === 0) {
      res.write(`data: ${JSON.stringify({ error: "I couldn't generate a valid query. Try a simpler question." })}\n\n`);
      return res.end();
    }

    // 3. run query
    let queryResult;
    try {
      queryResult = await Expense.aggregate(safePipeline);
    } catch (queryErr) {
      console.error("Query execution error:", queryErr.message);
      res.write(`data: ${JSON.stringify({ error: "The query failed to execute. Try rephrasing your question." })}\n\n`);
      return res.end();
    }

    // Send the data first so UI can use it
    res.write(`data: ${JSON.stringify({ type: "data", data: queryResult })}\n\n`);

    // 4. Generate stream
    const stream = await generateAnswerStream(message, queryResult);
    if (!stream) {
      res.write(`data: ${JSON.stringify({ error: "Couldn't generate an answer." })}\n\n`);
      return res.end();
    }

    // 5. Pipe stream to client
    for await (const chunk of stream) {
      if (chunk.text) {
        res.write(`data: ${JSON.stringify({ type: "text", text: chunk.text })}\n\n`);
      }
    }
    
    res.write(`data: ${JSON.stringify({ type: "done" })}\n\n`);
    res.end();
  } catch (err) {
    console.error("Chat stream error:", err);
    res.write(`data: ${JSON.stringify({ error: "Something went wrong." })}\n\n`);
    res.end();
  }
});
module.exports = router;
